Created the works and about me section
Leeoasis/My-Portfolio pull request #2
Opened 2023-01-13 17:46 UTC by Leeoasis

The following is an outline of the tasks I performed:

>Added the  works section with a display of the past projects completed.

> Added the About me section.

> Added the styling for both the works section and the about me section.

2023-01-13 19:53 UTC, Zuhaib042 requested changes
Hi @Leeoasis , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
✅ linters passing
✅ Professional PR

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] kindly consider writing commit messages in Imperative sentences. for example instead of writing `Added staying to ...`, you can write `Add styling to ...`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 19:53 UTC, Zuhaib042 commented on index.html
> +              <button>See Project</button>
- [x] This button should have a `:hover` and pressed state `:active` that change its color corresponding to the Figma design. you can check this link out and learn how to use these pseudo-classes. 
https://www.w3schools.com/cssref/sel_active.php
- [ ] Kindly consider applying these pseudo-classes per design guidelines to other `see project` buttons.

Figma design guidelines
![po](https://user-images.githubusercontent.com/96683843/212396780-dc4c24c5-ada2-4f85-9e84-a786feb7017c.jpg)

2023-01-13 19:53 UTC, Zuhaib042 commented on index.html
> +              <a href="#">Javascript</a>
- [ ] Kindly consider using a list `ul` tag here and each of these technologies should be a `li`.
- [ ] Kindly consider applying these changes across the cards as I can see the same pattern is repeating elsewhere.
- The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li

2023-01-13 19:53 UTC, Zuhaib042 commented on index.css
> +
- [ ] Kindly consider styling the Section of works with `display: grid` as it is a project requirement.
- The main container of the projects has a `display:grid`

2023-01-13 19:53 UTC, Zuhaib042 commented on index.html
> +      <div class="flex-container">
- [ ] This must be a `section` tag as mentioned in the requirements. kindly consider applying this change.
- The container of the section is a `section` tag

2023-01-13 19:53 UTC, Zuhaib042 commented on index.html
> +              <p class="icon">LET'S CONNECT</p>
- [ ] This must be a `h` header tag as this is for best semantic practices.
- If there are other titles (e.g., "Let's connect") use a header tag `hx`

2023-01-13 19:53 UTC, Zuhaib042 commented on index.html
> +              <button class="resume">Get my resume</button>
- [ ] Kindly consider styling this button with hover and active pseudo-class with corresponding design guidelines of colors.
- The button (e.g., "Get my resume") is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design)

2023-01-13 19:53 UTC, Zuhaib042 commented on index.css
> +  flex-direction: column;
- [ ] This section is not similar to the Figma design. Kindly consider exporting the background image of about section in Figma design and apply here in about section as `background-image`.
- [ ] Also consider applying button styling changes here as I mentioned  in the `see project` button.
you design
![asd](https://user-images.githubusercontent.com/96683843/212402971-49960770-8f98-4cd6-b8b3-70c88b926255.jpg)

figma design
![asdf](https://user-images.githubusercontent.com/96683843/212403034-d9af5ecd-d7db-4ccb-a153-3650f7c9ed3f.jpg)

2023-01-13 19:53 UTC, Zuhaib042 commented on index.html
> +        <div class="works-card">
- [ ] Kindly consider applying the following changes to your design to make it pixel-perfect to Figma design:
- [ ] The body of your project should have `#E5E5E5` color as seen in figma design.
- [ ] The `li`s under the title `CANOPY` are not properly aligned. kindly align them per figma design and also in other projects' cards.
- [ ] The `p` text in the Figma design has a lighter font weight. kindly consider fixing it.
your design
![qwer](https://user-images.githubusercontent.com/96683843/212404205-1f018da8-2521-4e26-9f61-e38f1b866bcf.jpg)


figma design
![qw](https://user-images.githubusercontent.com/96683843/212404069-729e7e3f-9dad-42c3-8301-f4c6f6006b96.jpg)

2023-01-13 19:53 UTC, Zuhaib042 commented on index.css
> +}
- [ ] This section of languages and Skills is not consistent with Figma design and overlapping. kindly consider changing it to make it similar to the Figma design as it is a project requirement.
your design
![zx](https://user-images.githubusercontent.com/96683843/212406272-b15c38d9-67bc-45a2-99b4-0b8fb242e88b.jpg)


figma design
![zxcv](https://user-images.githubusercontent.com/96683843/212406292-6535fb8c-c098-45dc-91c2-561beedb53dc.jpg)

2023-01-14 13:30 UTC, roshan-bajgain reviewed
Hi @Leeoasis, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a linter error please fix it and submit it again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-14 15:06 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @Leeoasis,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions
- This design has been either disturbed or was earlier not considered.
Suggestions:
 ```
 .languages_wrapper {
    padding: 12px 0px;
}

.first_buttons, .coding-languages ul {
    list-style: none;
    padding-left: 0px;
}
```
But keep in mind, that other things might not break.

![image](https://user-images.githubusercontent.com/61361037/212478400-561d45a9-85ab-43fd-9846-c283838b34df.png)

- _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 15:18 UTC, merged