My Portfolio desktop version
Leeoasis/My-Portfolio pull request #4
Opened 2023-01-19 18:41 UTC by Leeoasis

In this pull request, the following is an outline of tasks performed:

- Add desktop version markup in index.html.
- Add desktop foreground and background images.
- Add the desktop version styling.

2023-01-19 19:59 UTC, vickymarz requested changes
Hi @Leeoasis, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
-Good UI design ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 19:59 UTC, vickymarz commented on index.html
>          </nav>
- [ ] Good luck aligning your header section. Kindly adjust the height and padding around the navigation elements to match the figma design and also the color around the header 👍🏽. 

Figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213540082-a98a2a04-d5b3-499a-8c2b-4b2f90b01cc0.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213544179-dcb3a125-c2a0-4a59-9181-a4b5fa714cb7.png)

2023-01-19 19:59 UTC, vickymarz commented on index.html
>              <a class="logo" href="#">My Logo</a>
[OPTIONAL]

- I will recommend you replace this logo with your actual name, thereby personalizing your application 👍🏽 
![image](https://user-images.githubusercontent.com/63473584/213544574-9997b4cc-306c-4583-9000-7b48b30277d2.png)

2023-01-19 19:59 UTC, vickymarz commented on index.html
>      <section class="container">
- [ ] I will suggest you make sure that the background-image of the headline matches the figma design 👍🏽 

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213546121-7eabe7b2-12ed-47da-9be5-82b96ca4446b.png)

FIgma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213546236-8f2654e1-6689-4a47-99d7-95fa847f612c.png)

2023-01-19 19:59 UTC, vickymarz commented on index.html
> +        <h1 class="greeting-text">I am Leslie Glad to see you!</h1>
- [ ] KIndly break the content of this headline text to match the figma design 👍🏽 

Figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213546548-5c6e516c-676d-440a-a6dc-c62d1f3ed193.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213546670-0a25f94e-c8d9-4c79-a4c6-5594ea72a452.png)

2023-01-20 06:19 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @Leeoasis  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Linters are passing
- Used figms design correctly
- Used correct Github flow
## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 06:19 UTC, Nyame-Wolf commented on index.html
> +          </ul>
[OPTIONAL]I suggest you fix the mobile styling for your site. The headline section does not match the figma template. 
This is your design:
<img width="381" alt="Screenshot 2023-01-20 at 09 12 27" src="https://user-images.githubusercontent.com/48546992/213629952-b0fbf59a-7148-474e-959e-998acfe59f60.png">

this is the figma template:
<img width="381" alt="Screenshot 2023-01-19 at 09 40 33" src="https://user-images.githubusercontent.com/48546992/213630082-288af360-93cf-4ee9-b98d-5b01d898cb33.png">

Remember, that it's important to show that given a template, you can create a matching design.

2023-01-20 06:19 UTC, Nyame-Wolf commented on index.html
>              <textarea class="textarea-input" name="textarea" cols="30" rows="9"
[OPTIONAL] I suggest you change the place holders to `name` and `youremail@gmail.com`. Generalising it this way ensures that you increase its visibility plus avoid confusion especially for screen readers.

2023-01-20 06:30 UTC, merged